### ISSUE TITLE
[BUG] No Profiles listed in Settings (Ubuntu 24.04)

### ISSUE THREAD

**Issue by prodestrian** [dmy3k/auto-power-profile#16]
**Describe the bug**
I'm not sure if I'm doing something wrong here, but I don't have any Profiles listed in the Settings for this Extension.

**To Reproduce**

1. Install extension from Gnome Extensions Store (as per the README)
2. Open Gnome Extension Manager
3. Click the Settings icon next to Auto Power Profile
4. There are no Profiles listed for "On AC" or "On Battery"

**Expected behavior**
I expect to see a dropdown next to each containing a list of my three profiles (Performance, Balanced, and Power Saver).

**Screenshots**

![Image](https://github.com/user-attachments/assets/babcb29b-006d-4681-ad97-73b87b8343b4)

![Image](https://github.com/user-attachments/assets/2266e31a-847b-4431-98b6-c75886dc5b8c)

![Image](https://github.com/user-attachments/assets/12040ed7-695c-47ac-a99a-50451f5b20d4)

**Desktop (please complete the following information):**

- Ubuntu 24.04.2 LTS
- GNOME Shell 46.0
- Extension version 17

**Additional context**
This isn't a fresh install of Ubuntu 24.04, it was upgraded from 20.04 about a month ago. Not sure if that makes any difference. Hardware is a Lenovo laptop.

I've tried rebooting as well, no luck.

This is my complete list of installed Gnome Extensions, I don't think any of these should be interfering with this extension:

![Image](https://github.com/user-attachments/assets/a19bc685-3284-4b8d-bc18-2cde262c4af8)

I don't see any other similar issues on here, it seems to be working for everyone else.

Not sure if this is useful, but I ran `powerprofilesctl list` and got this output:
```
powerprofilesctl list        
  performance:
    CpuDriver:	intel_pstate
    PlatformDriver:	platform_profile
    Degraded:   no

* balanced:
    CpuDriver:	intel_pstate
    PlatformDriver:	platform_profile

  power-saver:
    CpuDriver:	intel_pstate
    PlatformDriver:	platform_profile
```

I've read the README from start to finish and I don't see anything obvious which might explain why this doesn't work for me. Is my system incompatible or did I overlook a critical step somewhere?

Thanks for any help you can provide.
